### ISSUE TITLE
🆕 Software Suggestion | URL Shorteners

### ISSUE THREAD

**Issue by subsign** [privacytoolsIO/privacytools.io#800]
## Basic Information

**Category:** URL Shorteners

## Description

Needed a URL shortener, first place I went to find one was privacytools.io.

I don't know what the community consensus is but I really don't want to use bitly or 
tinyurl. Any suggestions to this end might perhaps make for a new category?

**Comment by Mikaela** [comment]
I mostly use `jekyll-redirect` plugin with GitHub pages and have many files like this:

```yml
---
redirect_to: https://stackoverflow.com/q/413807
permalink: /r/1024.html
sitemap: false
---
```

I know that there are actual FOSS URL shorteners, but I don't remember any of their names.
